#docker-compose.yml
version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./js:/usr/share/nginx/html/app.js
      - ./css:/usr/share/nginx/html/css