#docker-compose.yml
version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./js:/usr/share/nginx/html/js
      - ./css:/usr/share/nginx/html/css
      - ./index.html:/usr/share/nginx/html/index.html