version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - server
  
  server:
    container_name: Todo
    build: .
    restart: always
    expose:
      - '5000'
